all:
	g++ -o test1 sourceTest1.cpp
	g++ -o test2 sourceTest2.cpp
	g++ -o test3 sourceTest3.cpp

# Не очень круто, но не хочу в пайплайне писать
test:
	./test1
	./test2
	./test3

clean: 
	rm test1
	rm test2
	rm test3
